import { Router, type IRouter } from "express";
import healthRouter from "./health";
import carsRouter from "./cars";
import bookingsRouter from "./bookings";
import availabilityRouter from "./availability";
import adminRouter from "./admin";
import contentRouter from "./content";
import seoRouter from "./seo";
import roomsRouter from "./rooms";
import sitemapRouter from "./sitemap";
import rentalVehiclesRouter from "./rental-vehicles";
import rentalAvailabilityBlocksRouter from "./rental-availability-blocks";
import rentalAddonsRouter from "./rental-addons";
import rentalReservationsRouter from "./rental-reservations";
import rentalOperationsRouter from "./rental-operations";
import rentalPrivateDocumentsRouter from "./rental-private-documents";
import operatorsRouter from "./operators";
import partnerRouter from "./partner";
import rentalRequestsRouter from "./rental-requests";
import rentalFinanceRouter from "./rental-finance";
import rentalTripRouter from "./rental-trip";
import rentalReservationExceptionsRouter from "./rental-reservation-exceptions";
import rentalExceptionsRouter from "./rental-exceptions";
import rentalCustomersRouter from "./rental-customers";

const router: IRouter = Router();

router.use(healthRouter);
router.use(carsRouter);
router.use(bookingsRouter);
router.use(availabilityRouter);
router.use(adminRouter);
router.use(contentRouter);
router.use(seoRouter);
router.use(roomsRouter);
router.use(sitemapRouter);
router.use(rentalVehiclesRouter);
router.use(rentalAvailabilityBlocksRouter);
router.use(rentalAddonsRouter);
router.use(rentalPrivateDocumentsRouter);
router.use(rentalTripRouter);
router.use(rentalReservationExceptionsRouter);
router.use(rentalExceptionsRouter);
router.use(rentalCustomersRouter);
router.use(rentalReservationsRouter);
router.use(rentalOperationsRouter);
router.use(operatorsRouter);
router.use(partnerRouter);
router.use(rentalRequestsRouter);
router.use(rentalFinanceRouter);

export default router;
